const PERMISSIONS = require("./PERMISSIONS");

const ROLES = [
  {
    name: "master",
    permissions: [
      PERMISSIONS.CREATE.COURSE,
      PERMISSIONS.UPDATE.COURSE,
      PERMISSIONS.PUBLISH.COURSE,
      PERMISSIONS.DELETE.COURSE,
      PERMISSIONS.CREATE.ADMIN,
      PERMISSIONS.UPDATE.ADMIN,
      PERMISSIONS.READ.ADMIN,
      PERMISSIONS.DELETE.ADMIN,
      PERMISSIONS.CREATE.MODULE,
      PERMISSIONS.UPDATE.MODULE,
      PERMISSIONS.DELETE.MODULE,
      PERMISSIONS.PUBLISH.MODULE,
      PERMISSIONS.UPLOAD.COURSE_IMAGE,
      PERMISSIONS.UPDATE.ROLE,
    ],
  },
  {
    name: "admin",
    permissions: [
      PERMISSIONS.CREATE.COURSE,
      PERMISSIONS.UPDATE.COURSE,
      PERMISSIONS.PUBLISH.COURSE,
      PERMISSIONS.CREATE.MODULE,
      PERMISSIONS.UPDATE.MODULE,
      PERMISSIONS.DELETE.MODULE,
      PERMISSIONS.PUBLISH.MODULE,
      PERMISSIONS.UPLOAD.COURSE_IMAGE,
    ],
  },
  {
    name: "editor",
    permissions: [
      PERMISSIONS.CREATE.COURSE,
      PERMISSIONS.UPDATE.COURSE,
      PERMISSIONS.CREATE.MODULE,
      PERMISSIONS.UPDATE.MODULE,
      PERMISSIONS.PUBLISH.MODULE,
      PERMISSIONS.UPLOAD.COURSE_IMAGE,
    ],
  },
  {
    name: "user",
    permissions: [
      // TODO: Delete test permissions
      PERMISSIONS.CREATE.COURSE,
      PERMISSIONS.UPDATE.COURSE,
      PERMISSIONS.PUBLISH.COURSE,
      PERMISSIONS.DELETE.COURSE,
      PERMISSIONS.CREATE.ADMIN,
      PERMISSIONS.UPDATE.ADMIN,
      PERMISSIONS.READ.ADMIN,
      PERMISSIONS.READ.USER,
      PERMISSIONS.DELETE.ADMIN,
      PERMISSIONS.CREATE.MODULE,
      PERMISSIONS.UPDATE.MODULE,
      PERMISSIONS.DELETE.MODULE,
      PERMISSIONS.PUBLISH.MODULE,
      PERMISSIONS.UPLOAD.COURSE_IMAGE,
      PERMISSIONS.UPDATE.ROLE,
    ],
  },
];

module.exports = ROLES;
